#!/bin/bash
# Run from repo root: bash rename_emblems.sh

# Fix wrong names in emblems/png/

# Israeli
mv "emblems/png/Al-Maghar_COA.png"                   "emblems/png/maghar-COA.png"
mv "emblems/png/Coat_of_arms_of_Tzur_haddash.png"    "emblems/png/zur-hadassa-COA.png"
mv "emblems/png/Jisr_az-Zarqa_local_council_COA.png" "emblems/png/jisr-az-zarqa-COA.png"
mv "emblems/png/kaokab-logo.png"                     "emblems/png/kawkab-abu-al-hija-COA.png"
mv "emblems/png/shaarey_tikva.png"                   "emblems/png/shaarei-tikva-COA.png"
mv "emblems/png/Yehud_COA.gif"                       "emblems/png/yehud-monosson-COA.gif"
mv "emblems/png/kedumim-logo.png"                    "emblems/png/kedumim-COA.png"
mv "emblems/png/modiin-region-COA.jpeg"              "emblems/png/modiin-region-COA.jpg"
mv "emblems/png/בוסתן אלמרג.jpeg"                   "emblems/png/bustan-al-marj-COA.jpg"
mv "emblems/png/בענה.jpeg"                           "emblems/png/bana-COA.jpg"
mv "emblems/png/דיר אל אסד.jpg"                     "emblems/png/deir-al-asad-COA.jpg"
mv "emblems/png/מגד אל כרום.jpg"                    "emblems/png/majd-al-krum-COA.jpg"
mv "emblems/png/מוונוסון לוגו.png"                  "emblems/png/neve-monosson-COA.png"
mv "emblems/png/מכבים-רעות.jpg"                     "emblems/png/maccabim-reut-COA-obsolete.jpg"
mv "emblems/png/beit shean.jpg"                      "emblems/png/beit-shean-COA.jpg"

# Palestinian
mv "emblems/png/al yamun.jpg"                        "emblems/png/ps-wb-al-yamun-COA.jpg"
mv "emblems/png/al-Ubeidiyya.jpg"                    "emblems/png/ps-wb-al-ubeidiyya-COA.jpg"
mv "emblems/png/alfuhari.jpg"                        "emblems/png/ps-gz-al-fukhari-COA.jpg"
mv "emblems/png/almaghazi.jpg"                       "emblems/png/ps-gz-al-maghazi-COA.jpg"
mv "emblems/png/anabta.jpg"                          "emblems/png/ps-wb-anabta-COA.jpg"
mv "emblems/png/Aqraba.jpg"                          "emblems/png/ps-wb-aqraba-COA.jpg"
mv "emblems/png/aram.jpg"                            "emblems/png/ps-wb-al-ram-COA.jpg"
mv "emblems/png/arraba.jpg"                          "emblems/png/ps-wb-arraba-COA.jpg"
mv "emblems/png/assira a shamia.jpg"                 "emblems/png/ps-wb-asira-ash-shamaliyya-COA.jpg"
mv "emblems/png/attil.jpg"                           "emblems/png/ps-wb-attil-COA.jpg"
mv "emblems/png/azzun.jpg"                           "emblems/png/ps-wb-azzun-COA.jpg"
mv "emblems/png/bani zaid.jpg"                       "emblems/png/ps-wb-qarawat-bani-zaid-COA.jpg"
mv "emblems/png/baqa al sharqia.jpg"                 "emblems/png/ps-wb-baqa-ash-sharqiyya-COA.jpg"
mv "emblems/png/battir.jpg"                          "emblems/png/ps-wb-battir-COA.jpg"
mv "emblems/png/beit fagar.jpg"                      "emblems/png/ps-wb-beit-fajjar-COA.jpg"
mv "emblems/png/beit furik.jpg"                      "emblems/png/ps-wb-beit-furik-COA.jpg"
mv "emblems/png/beit ur al tahta.jpg"                "emblems/png/ps-wb-beit-ur-al-tahta-COA.jpg"
mv "emblems/png/beitawwa.jpg"                        "emblems/png/ps-wb-beit-awwa-COA.jpg"
mv "emblems/png/bidya.jpg"                           "emblems/png/ps-wb-bidya-COA.jpg"
mv "emblems/png/bir zeit.png"                        "emblems/png/ps-wb-bir-zeit-COA.png"
mv "emblems/png/deir el balut.jpg"                   "emblems/png/ps-wb-deir-ballut-COA.jpg"
mv "emblems/png/gaza.jpg"                            "emblems/png/ps-gz-gaza-COA.jpg"
mv "emblems/png/howara.png"                          "emblems/png/ps-wb-huwwara-COA.png"
mv "emblems/png/jaba.jpg"                            "emblems/png/ps-wb-jaba-COA.jpg"
mv "emblems/png/jayyus.jpg"                          "emblems/png/ps-wb-jayyus-COA.jpg"
mv "emblems/png/jenin.png"                           "emblems/png/ps-wb-jenin-COA.png"
mv "emblems/png/khuzaa.png"                          "emblems/png/ps-gz-khuza-COA.png"
mv "emblems/png/kufr el deek.jpg"                    "emblems/png/ps-wb-kafr-ad-dik-COA.jpg"
mv "emblems/png/kufr rai.jpg"                        "emblems/png/ps-wb-kafr-rai-COA.jpg"
mv "emblems/png/nahlihn.jpg"                         "emblems/png/ps-wb-nahhalin-COA.jpg"
mv "emblems/png/nileen.jpg"                          "emblems/png/ps-wb-nilin-COA.jpg"
mv "emblems/png/nuseirat.jpg"                        "emblems/png/ps-gz-al-nuseirat-COA.jpg"
mv "emblems/png/qarara.jpg"                          "emblems/png/ps-gz-al-qarara-COA.jpg"
mv "emblems/png/qarawat bani hassan.jpg"             "emblems/png/ps-wb-qarawat-bani-hassan-COA.jpg"
mv "emblems/png/Seal_of_Deir_al-Balah.tif.png"      "emblems/png/ps-gz-deir-al-balah-COA.png"
mv "emblems/png/sebastia.jpg"                        "emblems/png/ps-wb-sebastia-COA.jpg"
mv "emblems/png/silwad.jpg"                          "emblems/png/ps-wb-silwad-COA.jpg"
mv "emblems/png/sinjil.jpg"                          "emblems/png/ps-wb-sinjil-COA.jpg"
mv "emblems/png/tafuch.jpg"                          "emblems/png/ps-wb-taffuh-COA.jpg"
mv "emblems/png/tammun.jpg"                          "emblems/png/ps-wb-tammun-COA.jpg"
mv "emblems/png/tarqumiya.jpg"                       "emblems/png/ps-wb-tarqumiyah-COA.jpg"
mv "emblems/png/tuqo.jpg"                            "emblems/png/ps-wb-tuqu-COA.jpg"
mv "emblems/png/turmosia.jpg"                        "emblems/png/ps-wb-turmusayya-COA.jpg"
mv "emblems/png/tzurif.jpg"                          "emblems/png/ps-wb-surif-COA.jpg"
mv "emblems/png/yabad.jpg"                           "emblems/png/ps-wb-yabad-COA.jpg"
mv "emblems/png/zawaida.jpg"                         "emblems/png/ps-gz-zawaida-COA.jpg"

# Delete duplicates
rm -f "emblems/png/anabta copy.jpg"

echo "Done."
